/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalAccountantBillingRouteImport } from './routes/_portal.accountant.billing'
import { Route as PortalAccountantClosureRouteImport } from './routes/_portal.accountant.closure'
import { Route as PortalAccountantDashboardRouteImport } from './routes/_portal.accountant.dashboard'
import { Route as PortalAccountantFinancialYearRouteImport } from './routes/_portal.accountant.financial-year'
import { Route as PortalAccountantNotificationsRouteImport } from './routes/_portal.accountant.notifications'
import { Route as PortalAccountantReportsRouteImport } from './routes/_portal.accountant.reports'
import { Route as PortalAdminAuditRouteImport } from './routes/_portal.admin.audit'
import { Route as PortalAdminDashboardRouteImport } from './routes/_portal.admin.dashboard'
import { Route as PortalAdminFinancialYearRouteImport } from './routes/_portal.admin.financial-year'
import { Route as PortalAdminOrdersRouteImport } from './routes/_portal.admin.orders'
import { Route as PortalAdminReportsRouteImport } from './routes/_portal.admin.reports'
import { Route as PortalAdminSettingsRouteImport } from './routes/_portal.admin.settings'
import { Route as PortalAdminUsersRouteImport } from './routes/_portal.admin.users'
import { Route as PortalEmployeeDashboardRouteImport } from './routes/_portal.employee.dashboard'
import { Route as PortalEmployeeNewOrderRouteImport } from './routes/_portal.employee.new-order'
import { Route as PortalEmployeeNotificationsRouteImport } from './routes/_portal.employee.notifications'
import { Route as PortalEmployeeOrdersRouteImport } from './routes/_portal.employee.orders'
import { Route as PortalEmployeeProfileRouteImport } from './routes/_portal.employee.profile'
import { Route as PortalProductionDashboardRouteImport } from './routes/_portal.production.dashboard'
import { Route as PortalProductionNotificationsRouteImport } from './routes/_portal.production.notifications'
import { Route as PortalProductionQueueRouteImport } from './routes/_portal.production.queue'
import { Route as PortalProductionRemarksRouteImport } from './routes/_portal.production.remarks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAccountantBillingRoute = PortalAccountantBillingRouteImport.update({
  id: '/accountant/billing',
  path: '/accountant/billing',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountantClosureRoute = PortalAccountantClosureRouteImport.update({
  id: '/accountant/closure',
  path: '/accountant/closure',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountantDashboardRoute =
  PortalAccountantDashboardRouteImport.update({
    id: '/accountant/dashboard',
    path: '/accountant/dashboard',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountantFinancialYearRoute =
  PortalAccountantFinancialYearRouteImport.update({
    id: '/accountant/financial-year',
    path: '/accountant/financial-year',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountantNotificationsRoute =
  PortalAccountantNotificationsRouteImport.update({
    id: '/accountant/notifications',
    path: '/accountant/notifications',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountantReportsRoute = PortalAccountantReportsRouteImport.update({
  id: '/accountant/reports',
  path: '/accountant/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminAuditRoute = PortalAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminDashboardRoute = PortalAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminFinancialYearRoute =
  PortalAdminFinancialYearRouteImport.update({
    id: '/admin/financial-year',
    path: '/admin/financial-year',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAdminOrdersRoute = PortalAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminReportsRoute = PortalAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminSettingsRoute = PortalAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminUsersRoute = PortalAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEmployeeDashboardRoute = PortalEmployeeDashboardRouteImport.update({
  id: '/employee/dashboard',
  path: '/employee/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEmployeeNewOrderRoute = PortalEmployeeNewOrderRouteImport.update({
  id: '/employee/new-order',
  path: '/employee/new-order',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEmployeeNotificationsRoute =
  PortalEmployeeNotificationsRouteImport.update({
    id: '/employee/notifications',
    path: '/employee/notifications',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalEmployeeOrdersRoute = PortalEmployeeOrdersRouteImport.update({
  id: '/employee/orders',
  path: '/employee/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEmployeeProfileRoute = PortalEmployeeProfileRouteImport.update({
  id: '/employee/profile',
  path: '/employee/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProductionDashboardRoute =
  PortalProductionDashboardRouteImport.update({
    id: '/production/dashboard',
    path: '/production/dashboard',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalProductionNotificationsRoute =
  PortalProductionNotificationsRouteImport.update({
    id: '/production/notifications',
    path: '/production/notifications',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalProductionQueueRoute = PortalProductionQueueRouteImport.update({
  id: '/production/queue',
  path: '/production/queue',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProductionRemarksRoute = PortalProductionRemarksRouteImport.update({
  id: '/production/remarks',
  path: '/production/remarks',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accountant/billing': typeof PortalAccountantBillingRoute
  '/accountant/closure': typeof PortalAccountantClosureRoute
  '/accountant/dashboard': typeof PortalAccountantDashboardRoute
  '/accountant/financial-year': typeof PortalAccountantFinancialYearRoute
  '/accountant/notifications': typeof PortalAccountantNotificationsRoute
  '/accountant/reports': typeof PortalAccountantReportsRoute
  '/admin/audit': typeof PortalAdminAuditRoute
  '/admin/dashboard': typeof PortalAdminDashboardRoute
  '/admin/financial-year': typeof PortalAdminFinancialYearRoute
  '/admin/orders': typeof PortalAdminOrdersRoute
  '/admin/reports': typeof PortalAdminReportsRoute
  '/admin/settings': typeof PortalAdminSettingsRoute
  '/admin/users': typeof PortalAdminUsersRoute
  '/employee/dashboard': typeof PortalEmployeeDashboardRoute
  '/employee/new-order': typeof PortalEmployeeNewOrderRoute
  '/employee/notifications': typeof PortalEmployeeNotificationsRoute
  '/employee/orders': typeof PortalEmployeeOrdersRoute
  '/employee/profile': typeof PortalEmployeeProfileRoute
  '/production/dashboard': typeof PortalProductionDashboardRoute
  '/production/notifications': typeof PortalProductionNotificationsRoute
  '/production/queue': typeof PortalProductionQueueRoute
  '/production/remarks': typeof PortalProductionRemarksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accountant/billing': typeof PortalAccountantBillingRoute
  '/accountant/closure': typeof PortalAccountantClosureRoute
  '/accountant/dashboard': typeof PortalAccountantDashboardRoute
  '/accountant/financial-year': typeof PortalAccountantFinancialYearRoute
  '/accountant/notifications': typeof PortalAccountantNotificationsRoute
  '/accountant/reports': typeof PortalAccountantReportsRoute
  '/admin/audit': typeof PortalAdminAuditRoute
  '/admin/dashboard': typeof PortalAdminDashboardRoute
  '/admin/financial-year': typeof PortalAdminFinancialYearRoute
  '/admin/orders': typeof PortalAdminOrdersRoute
  '/admin/reports': typeof PortalAdminReportsRoute
  '/admin/settings': typeof PortalAdminSettingsRoute
  '/admin/users': typeof PortalAdminUsersRoute
  '/employee/dashboard': typeof PortalEmployeeDashboardRoute
  '/employee/new-order': typeof PortalEmployeeNewOrderRoute
  '/employee/notifications': typeof PortalEmployeeNotificationsRoute
  '/employee/orders': typeof PortalEmployeeOrdersRoute
  '/employee/profile': typeof PortalEmployeeProfileRoute
  '/production/dashboard': typeof PortalProductionDashboardRoute
  '/production/notifications': typeof PortalProductionNotificationsRoute
  '/production/queue': typeof PortalProductionQueueRoute
  '/production/remarks': typeof PortalProductionRemarksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/login': typeof LoginRoute
  '/_portal/accountant/billing': typeof PortalAccountantBillingRoute
  '/_portal/accountant/closure': typeof PortalAccountantClosureRoute
  '/_portal/accountant/dashboard': typeof PortalAccountantDashboardRoute
  '/_portal/accountant/financial-year': typeof PortalAccountantFinancialYearRoute
  '/_portal/accountant/notifications': typeof PortalAccountantNotificationsRoute
  '/_portal/accountant/reports': typeof PortalAccountantReportsRoute
  '/_portal/admin/audit': typeof PortalAdminAuditRoute
  '/_portal/admin/dashboard': typeof PortalAdminDashboardRoute
  '/_portal/admin/financial-year': typeof PortalAdminFinancialYearRoute
  '/_portal/admin/orders': typeof PortalAdminOrdersRoute
  '/_portal/admin/reports': typeof PortalAdminReportsRoute
  '/_portal/admin/settings': typeof PortalAdminSettingsRoute
  '/_portal/admin/users': typeof PortalAdminUsersRoute
  '/_portal/employee/dashboard': typeof PortalEmployeeDashboardRoute
  '/_portal/employee/new-order': typeof PortalEmployeeNewOrderRoute
  '/_portal/employee/notifications': typeof PortalEmployeeNotificationsRoute
  '/_portal/employee/orders': typeof PortalEmployeeOrdersRoute
  '/_portal/employee/profile': typeof PortalEmployeeProfileRoute
  '/_portal/production/dashboard': typeof PortalProductionDashboardRoute
  '/_portal/production/notifications': typeof PortalProductionNotificationsRoute
  '/_portal/production/queue': typeof PortalProductionQueueRoute
  '/_portal/production/remarks': typeof PortalProductionRemarksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accountant/billing'
    | '/accountant/closure'
    | '/accountant/dashboard'
    | '/accountant/financial-year'
    | '/accountant/notifications'
    | '/accountant/reports'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/financial-year'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/employee/dashboard'
    | '/employee/new-order'
    | '/employee/notifications'
    | '/employee/orders'
    | '/employee/profile'
    | '/production/dashboard'
    | '/production/notifications'
    | '/production/queue'
    | '/production/remarks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accountant/billing'
    | '/accountant/closure'
    | '/accountant/dashboard'
    | '/accountant/financial-year'
    | '/accountant/notifications'
    | '/accountant/reports'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/financial-year'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/employee/dashboard'
    | '/employee/new-order'
    | '/employee/notifications'
    | '/employee/orders'
    | '/employee/profile'
    | '/production/dashboard'
    | '/production/notifications'
    | '/production/queue'
    | '/production/remarks'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/login'
    | '/_portal/accountant/billing'
    | '/_portal/accountant/closure'
    | '/_portal/accountant/dashboard'
    | '/_portal/accountant/financial-year'
    | '/_portal/accountant/notifications'
    | '/_portal/accountant/reports'
    | '/_portal/admin/audit'
    | '/_portal/admin/dashboard'
    | '/_portal/admin/financial-year'
    | '/_portal/admin/orders'
    | '/_portal/admin/reports'
    | '/_portal/admin/settings'
    | '/_portal/admin/users'
    | '/_portal/employee/dashboard'
    | '/_portal/employee/new-order'
    | '/_portal/employee/notifications'
    | '/_portal/employee/orders'
    | '/_portal/employee/profile'
    | '/_portal/production/dashboard'
    | '/_portal/production/notifications'
    | '/_portal/production/queue'
    | '/_portal/production/remarks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/accountant/billing': {
      id: '/_portal/accountant/billing'
      path: '/accountant/billing'
      fullPath: '/accountant/billing'
      preLoaderRoute: typeof PortalAccountantBillingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/closure': {
      id: '/_portal/accountant/closure'
      path: '/accountant/closure'
      fullPath: '/accountant/closure'
      preLoaderRoute: typeof PortalAccountantClosureRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/dashboard': {
      id: '/_portal/accountant/dashboard'
      path: '/accountant/dashboard'
      fullPath: '/accountant/dashboard'
      preLoaderRoute: typeof PortalAccountantDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/financial-year': {
      id: '/_portal/accountant/financial-year'
      path: '/accountant/financial-year'
      fullPath: '/accountant/financial-year'
      preLoaderRoute: typeof PortalAccountantFinancialYearRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/notifications': {
      id: '/_portal/accountant/notifications'
      path: '/accountant/notifications'
      fullPath: '/accountant/notifications'
      preLoaderRoute: typeof PortalAccountantNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/reports': {
      id: '/_portal/accountant/reports'
      path: '/accountant/reports'
      fullPath: '/accountant/reports'
      preLoaderRoute: typeof PortalAccountantReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/audit': {
      id: '/_portal/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof PortalAdminAuditRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/dashboard': {
      id: '/_portal/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof PortalAdminDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/financial-year': {
      id: '/_portal/admin/financial-year'
      path: '/admin/financial-year'
      fullPath: '/admin/financial-year'
      preLoaderRoute: typeof PortalAdminFinancialYearRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/orders': {
      id: '/_portal/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof PortalAdminOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/reports': {
      id: '/_portal/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof PortalAdminReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/settings': {
      id: '/_portal/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof PortalAdminSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/users': {
      id: '/_portal/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof PortalAdminUsersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/dashboard': {
      id: '/_portal/employee/dashboard'
      path: '/employee/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof PortalEmployeeDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/new-order': {
      id: '/_portal/employee/new-order'
      path: '/employee/new-order'
      fullPath: '/employee/new-order'
      preLoaderRoute: typeof PortalEmployeeNewOrderRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/notifications': {
      id: '/_portal/employee/notifications'
      path: '/employee/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof PortalEmployeeNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/orders': {
      id: '/_portal/employee/orders'
      path: '/employee/orders'
      fullPath: '/employee/orders'
      preLoaderRoute: typeof PortalEmployeeOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/profile': {
      id: '/_portal/employee/profile'
      path: '/employee/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof PortalEmployeeProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/production/dashboard': {
      id: '/_portal/production/dashboard'
      path: '/production/dashboard'
      fullPath: '/production/dashboard'
      preLoaderRoute: typeof PortalProductionDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/production/notifications': {
      id: '/_portal/production/notifications'
      path: '/production/notifications'
      fullPath: '/production/notifications'
      preLoaderRoute: typeof PortalProductionNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/production/queue': {
      id: '/_portal/production/queue'
      path: '/production/queue'
      fullPath: '/production/queue'
      preLoaderRoute: typeof PortalProductionQueueRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/production/remarks': {
      id: '/_portal/production/remarks'
      path: '/production/remarks'
      fullPath: '/production/remarks'
      preLoaderRoute: typeof PortalProductionRemarksRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAccountantBillingRoute: typeof PortalAccountantBillingRoute
  PortalAccountantClosureRoute: typeof PortalAccountantClosureRoute
  PortalAccountantDashboardRoute: typeof PortalAccountantDashboardRoute
  PortalAccountantFinancialYearRoute: typeof PortalAccountantFinancialYearRoute
  PortalAccountantNotificationsRoute: typeof PortalAccountantNotificationsRoute
  PortalAccountantReportsRoute: typeof PortalAccountantReportsRoute
  PortalAdminAuditRoute: typeof PortalAdminAuditRoute
  PortalAdminDashboardRoute: typeof PortalAdminDashboardRoute
  PortalAdminFinancialYearRoute: typeof PortalAdminFinancialYearRoute
  PortalAdminOrdersRoute: typeof PortalAdminOrdersRoute
  PortalAdminReportsRoute: typeof PortalAdminReportsRoute
  PortalAdminSettingsRoute: typeof PortalAdminSettingsRoute
  PortalAdminUsersRoute: typeof PortalAdminUsersRoute
  PortalEmployeeDashboardRoute: typeof PortalEmployeeDashboardRoute
  PortalEmployeeNewOrderRoute: typeof PortalEmployeeNewOrderRoute
  PortalEmployeeNotificationsRoute: typeof PortalEmployeeNotificationsRoute
  PortalEmployeeOrdersRoute: typeof PortalEmployeeOrdersRoute
  PortalEmployeeProfileRoute: typeof PortalEmployeeProfileRoute
  PortalProductionDashboardRoute: typeof PortalProductionDashboardRoute
  PortalProductionNotificationsRoute: typeof PortalProductionNotificationsRoute
  PortalProductionQueueRoute: typeof PortalProductionQueueRoute
  PortalProductionRemarksRoute: typeof PortalProductionRemarksRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountantBillingRoute: PortalAccountantBillingRoute,
  PortalAccountantClosureRoute: PortalAccountantClosureRoute,
  PortalAccountantDashboardRoute: PortalAccountantDashboardRoute,
  PortalAccountantFinancialYearRoute: PortalAccountantFinancialYearRoute,
  PortalAccountantNotificationsRoute: PortalAccountantNotificationsRoute,
  PortalAccountantReportsRoute: PortalAccountantReportsRoute,
  PortalAdminAuditRoute: PortalAdminAuditRoute,
  PortalAdminDashboardRoute: PortalAdminDashboardRoute,
  PortalAdminFinancialYearRoute: PortalAdminFinancialYearRoute,
  PortalAdminOrdersRoute: PortalAdminOrdersRoute,
  PortalAdminReportsRoute: PortalAdminReportsRoute,
  PortalAdminSettingsRoute: PortalAdminSettingsRoute,
  PortalAdminUsersRoute: PortalAdminUsersRoute,
  PortalEmployeeDashboardRoute: PortalEmployeeDashboardRoute,
  PortalEmployeeNewOrderRoute: PortalEmployeeNewOrderRoute,
  PortalEmployeeNotificationsRoute: PortalEmployeeNotificationsRoute,
  PortalEmployeeOrdersRoute: PortalEmployeeOrdersRoute,
  PortalEmployeeProfileRoute: PortalEmployeeProfileRoute,
  PortalProductionDashboardRoute: PortalProductionDashboardRoute,
  PortalProductionNotificationsRoute: PortalProductionNotificationsRoute,
  PortalProductionQueueRoute: PortalProductionQueueRoute,
  PortalProductionRemarksRoute: PortalProductionRemarksRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
