/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalProfileRouteImport } from './routes/_portal.profile'
import { Route as PortalAccountantBillingRouteImport } from './routes/_portal.accountant.billing'
import { Route as PortalAccountantDashboardRouteImport } from './routes/_portal.accountant.dashboard'
import { Route as PortalAccountantFinancialYearRouteImport } from './routes/_portal.accountant.financial-year'
import { Route as PortalAccountantNotificationsRouteImport } from './routes/_portal.accountant.notifications'
import { Route as PortalAccountantOrdersRouteImport } from './routes/_portal.accountant.orders'
import { Route as PortalAccountantReportsRouteImport } from './routes/_portal.accountant.reports'
import { Route as PortalAdminAuditRouteImport } from './routes/_portal.admin.audit'
import { Route as PortalAdminDashboardRouteImport } from './routes/_portal.admin.dashboard'
import { Route as PortalAdminFinancialYearRouteImport } from './routes/_portal.admin.financial-year'
import { Route as PortalAdminOrdersRouteImport } from './routes/_portal.admin.orders'
import { Route as PortalAdminReportsRouteImport } from './routes/_portal.admin.reports'
import { Route as PortalAdminSettingsRouteImport } from './routes/_portal.admin.settings'
import { Route as PortalAdminUsersRouteImport } from './routes/_portal.admin.users'
import { Route as PortalEmployeeDashboardRouteImport } from './routes/_portal.employee.dashboard'
import { Route as PortalEmployeeNewOrderRouteImport } from './routes/_portal.employee.new-order'
import { Route as PortalEmployeeNotificationsRouteImport } from './routes/_portal.employee.notifications'
import { Route as PortalEmployeeOrdersRouteImport } from './routes/_portal.employee.orders'
import { Route as PortalProductionDashboardRouteImport } from './routes/_portal.production.dashboard'
import { Route as PortalProductionNotificationsRouteImport } from './routes/_portal.production.notifications'
import { Route as PortalProductionQueueRouteImport } from './routes/_portal.production.queue'
import { Route as PortalAccountantBillingIdRouteImport } from './routes/_portal.accountant.billing_.$id'
import { Route as PortalAdminEditOrderIdRouteImport } from './routes/_portal.admin.edit-order.$id'
import { Route as PortalAdminOrdersIdRouteImport } from './routes/_portal.admin.orders_.$id'
import { Route as PortalEmployeeEditOrderIdRouteImport } from './routes/_portal.employee.edit-order.$id'
import { Route as PortalEmployeeOrdersIdRouteImport } from './routes/_portal.employee.orders_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountantBillingRoute = PortalAccountantBillingRouteImport.update({
  id: '/accountant/billing',
  path: '/accountant/billing',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountantDashboardRoute =
  PortalAccountantDashboardRouteImport.update({
    id: '/accountant/dashboard',
    path: '/accountant/dashboard',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountantFinancialYearRoute =
  PortalAccountantFinancialYearRouteImport.update({
    id: '/accountant/financial-year',
    path: '/accountant/financial-year',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountantNotificationsRoute =
  PortalAccountantNotificationsRouteImport.update({
    id: '/accountant/notifications',
    path: '/accountant/notifications',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountantOrdersRoute = PortalAccountantOrdersRouteImport.update({
  id: '/accountant/orders',
  path: '/accountant/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountantReportsRoute = PortalAccountantReportsRouteImport.update({
  id: '/accountant/reports',
  path: '/accountant/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminAuditRoute = PortalAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminDashboardRoute = PortalAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminFinancialYearRoute =
  PortalAdminFinancialYearRouteImport.update({
    id: '/admin/financial-year',
    path: '/admin/financial-year',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAdminOrdersRoute = PortalAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminReportsRoute = PortalAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminSettingsRoute = PortalAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminUsersRoute = PortalAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEmployeeDashboardRoute = PortalEmployeeDashboardRouteImport.update({
  id: '/employee/dashboard',
  path: '/employee/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEmployeeNewOrderRoute = PortalEmployeeNewOrderRouteImport.update({
  id: '/employee/new-order',
  path: '/employee/new-order',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEmployeeNotificationsRoute =
  PortalEmployeeNotificationsRouteImport.update({
    id: '/employee/notifications',
    path: '/employee/notifications',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalEmployeeOrdersRoute = PortalEmployeeOrdersRouteImport.update({
  id: '/employee/orders',
  path: '/employee/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProductionDashboardRoute =
  PortalProductionDashboardRouteImport.update({
    id: '/production/dashboard',
    path: '/production/dashboard',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalProductionNotificationsRoute =
  PortalProductionNotificationsRouteImport.update({
    id: '/production/notifications',
    path: '/production/notifications',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalProductionQueueRoute = PortalProductionQueueRouteImport.update({
  id: '/production/queue',
  path: '/production/queue',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountantBillingIdRoute =
  PortalAccountantBillingIdRouteImport.update({
    id: '/accountant/billing_/$id',
    path: '/accountant/billing/$id',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAdminEditOrderIdRoute = PortalAdminEditOrderIdRouteImport.update({
  id: '/admin/edit-order/$id',
  path: '/admin/edit-order/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminOrdersIdRoute = PortalAdminOrdersIdRouteImport.update({
  id: '/admin/orders_/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEmployeeEditOrderIdRoute =
  PortalEmployeeEditOrderIdRouteImport.update({
    id: '/employee/edit-order/$id',
    path: '/employee/edit-order/$id',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalEmployeeOrdersIdRoute = PortalEmployeeOrdersIdRouteImport.update({
  id: '/employee/orders_/$id',
  path: '/employee/orders/$id',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof PortalProfileRoute
  '/accountant/billing': typeof PortalAccountantBillingRoute
  '/accountant/dashboard': typeof PortalAccountantDashboardRoute
  '/accountant/financial-year': typeof PortalAccountantFinancialYearRoute
  '/accountant/notifications': typeof PortalAccountantNotificationsRoute
  '/accountant/orders': typeof PortalAccountantOrdersRoute
  '/accountant/reports': typeof PortalAccountantReportsRoute
  '/admin/audit': typeof PortalAdminAuditRoute
  '/admin/dashboard': typeof PortalAdminDashboardRoute
  '/admin/financial-year': typeof PortalAdminFinancialYearRoute
  '/admin/orders': typeof PortalAdminOrdersRoute
  '/admin/reports': typeof PortalAdminReportsRoute
  '/admin/settings': typeof PortalAdminSettingsRoute
  '/admin/users': typeof PortalAdminUsersRoute
  '/employee/dashboard': typeof PortalEmployeeDashboardRoute
  '/employee/new-order': typeof PortalEmployeeNewOrderRoute
  '/employee/notifications': typeof PortalEmployeeNotificationsRoute
  '/employee/orders': typeof PortalEmployeeOrdersRoute
  '/production/dashboard': typeof PortalProductionDashboardRoute
  '/production/notifications': typeof PortalProductionNotificationsRoute
  '/production/queue': typeof PortalProductionQueueRoute
  '/accountant/billing/$id': typeof PortalAccountantBillingIdRoute
  '/admin/edit-order/$id': typeof PortalAdminEditOrderIdRoute
  '/admin/orders/$id': typeof PortalAdminOrdersIdRoute
  '/employee/edit-order/$id': typeof PortalEmployeeEditOrderIdRoute
  '/employee/orders/$id': typeof PortalEmployeeOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof PortalProfileRoute
  '/accountant/billing': typeof PortalAccountantBillingRoute
  '/accountant/dashboard': typeof PortalAccountantDashboardRoute
  '/accountant/financial-year': typeof PortalAccountantFinancialYearRoute
  '/accountant/notifications': typeof PortalAccountantNotificationsRoute
  '/accountant/orders': typeof PortalAccountantOrdersRoute
  '/accountant/reports': typeof PortalAccountantReportsRoute
  '/admin/audit': typeof PortalAdminAuditRoute
  '/admin/dashboard': typeof PortalAdminDashboardRoute
  '/admin/financial-year': typeof PortalAdminFinancialYearRoute
  '/admin/orders': typeof PortalAdminOrdersRoute
  '/admin/reports': typeof PortalAdminReportsRoute
  '/admin/settings': typeof PortalAdminSettingsRoute
  '/admin/users': typeof PortalAdminUsersRoute
  '/employee/dashboard': typeof PortalEmployeeDashboardRoute
  '/employee/new-order': typeof PortalEmployeeNewOrderRoute
  '/employee/notifications': typeof PortalEmployeeNotificationsRoute
  '/employee/orders': typeof PortalEmployeeOrdersRoute
  '/production/dashboard': typeof PortalProductionDashboardRoute
  '/production/notifications': typeof PortalProductionNotificationsRoute
  '/production/queue': typeof PortalProductionQueueRoute
  '/accountant/billing/$id': typeof PortalAccountantBillingIdRoute
  '/admin/edit-order/$id': typeof PortalAdminEditOrderIdRoute
  '/admin/orders/$id': typeof PortalAdminOrdersIdRoute
  '/employee/edit-order/$id': typeof PortalEmployeeEditOrderIdRoute
  '/employee/orders/$id': typeof PortalEmployeeOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/login': typeof LoginRoute
  '/_portal/profile': typeof PortalProfileRoute
  '/_portal/accountant/billing': typeof PortalAccountantBillingRoute
  '/_portal/accountant/dashboard': typeof PortalAccountantDashboardRoute
  '/_portal/accountant/financial-year': typeof PortalAccountantFinancialYearRoute
  '/_portal/accountant/notifications': typeof PortalAccountantNotificationsRoute
  '/_portal/accountant/orders': typeof PortalAccountantOrdersRoute
  '/_portal/accountant/reports': typeof PortalAccountantReportsRoute
  '/_portal/admin/audit': typeof PortalAdminAuditRoute
  '/_portal/admin/dashboard': typeof PortalAdminDashboardRoute
  '/_portal/admin/financial-year': typeof PortalAdminFinancialYearRoute
  '/_portal/admin/orders': typeof PortalAdminOrdersRoute
  '/_portal/admin/reports': typeof PortalAdminReportsRoute
  '/_portal/admin/settings': typeof PortalAdminSettingsRoute
  '/_portal/admin/users': typeof PortalAdminUsersRoute
  '/_portal/employee/dashboard': typeof PortalEmployeeDashboardRoute
  '/_portal/employee/new-order': typeof PortalEmployeeNewOrderRoute
  '/_portal/employee/notifications': typeof PortalEmployeeNotificationsRoute
  '/_portal/employee/orders': typeof PortalEmployeeOrdersRoute
  '/_portal/production/dashboard': typeof PortalProductionDashboardRoute
  '/_portal/production/notifications': typeof PortalProductionNotificationsRoute
  '/_portal/production/queue': typeof PortalProductionQueueRoute
  '/_portal/accountant/billing_/$id': typeof PortalAccountantBillingIdRoute
  '/_portal/admin/edit-order/$id': typeof PortalAdminEditOrderIdRoute
  '/_portal/admin/orders_/$id': typeof PortalAdminOrdersIdRoute
  '/_portal/employee/edit-order/$id': typeof PortalEmployeeEditOrderIdRoute
  '/_portal/employee/orders_/$id': typeof PortalEmployeeOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/accountant/billing'
    | '/accountant/dashboard'
    | '/accountant/financial-year'
    | '/accountant/notifications'
    | '/accountant/orders'
    | '/accountant/reports'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/financial-year'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/employee/dashboard'
    | '/employee/new-order'
    | '/employee/notifications'
    | '/employee/orders'
    | '/production/dashboard'
    | '/production/notifications'
    | '/production/queue'
    | '/accountant/billing/$id'
    | '/admin/edit-order/$id'
    | '/admin/orders/$id'
    | '/employee/edit-order/$id'
    | '/employee/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/accountant/billing'
    | '/accountant/dashboard'
    | '/accountant/financial-year'
    | '/accountant/notifications'
    | '/accountant/orders'
    | '/accountant/reports'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/financial-year'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/employee/dashboard'
    | '/employee/new-order'
    | '/employee/notifications'
    | '/employee/orders'
    | '/production/dashboard'
    | '/production/notifications'
    | '/production/queue'
    | '/accountant/billing/$id'
    | '/admin/edit-order/$id'
    | '/admin/orders/$id'
    | '/employee/edit-order/$id'
    | '/employee/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/login'
    | '/_portal/profile'
    | '/_portal/accountant/billing'
    | '/_portal/accountant/dashboard'
    | '/_portal/accountant/financial-year'
    | '/_portal/accountant/notifications'
    | '/_portal/accountant/orders'
    | '/_portal/accountant/reports'
    | '/_portal/admin/audit'
    | '/_portal/admin/dashboard'
    | '/_portal/admin/financial-year'
    | '/_portal/admin/orders'
    | '/_portal/admin/reports'
    | '/_portal/admin/settings'
    | '/_portal/admin/users'
    | '/_portal/employee/dashboard'
    | '/_portal/employee/new-order'
    | '/_portal/employee/notifications'
    | '/_portal/employee/orders'
    | '/_portal/production/dashboard'
    | '/_portal/production/notifications'
    | '/_portal/production/queue'
    | '/_portal/accountant/billing_/$id'
    | '/_portal/admin/edit-order/$id'
    | '/_portal/admin/orders_/$id'
    | '/_portal/employee/edit-order/$id'
    | '/_portal/employee/orders_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/profile': {
      id: '/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/billing': {
      id: '/_portal/accountant/billing'
      path: '/accountant/billing'
      fullPath: '/accountant/billing'
      preLoaderRoute: typeof PortalAccountantBillingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/dashboard': {
      id: '/_portal/accountant/dashboard'
      path: '/accountant/dashboard'
      fullPath: '/accountant/dashboard'
      preLoaderRoute: typeof PortalAccountantDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/financial-year': {
      id: '/_portal/accountant/financial-year'
      path: '/accountant/financial-year'
      fullPath: '/accountant/financial-year'
      preLoaderRoute: typeof PortalAccountantFinancialYearRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/notifications': {
      id: '/_portal/accountant/notifications'
      path: '/accountant/notifications'
      fullPath: '/accountant/notifications'
      preLoaderRoute: typeof PortalAccountantNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/orders': {
      id: '/_portal/accountant/orders'
      path: '/accountant/orders'
      fullPath: '/accountant/orders'
      preLoaderRoute: typeof PortalAccountantOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/reports': {
      id: '/_portal/accountant/reports'
      path: '/accountant/reports'
      fullPath: '/accountant/reports'
      preLoaderRoute: typeof PortalAccountantReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/audit': {
      id: '/_portal/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof PortalAdminAuditRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/dashboard': {
      id: '/_portal/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof PortalAdminDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/financial-year': {
      id: '/_portal/admin/financial-year'
      path: '/admin/financial-year'
      fullPath: '/admin/financial-year'
      preLoaderRoute: typeof PortalAdminFinancialYearRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/orders': {
      id: '/_portal/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof PortalAdminOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/reports': {
      id: '/_portal/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof PortalAdminReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/settings': {
      id: '/_portal/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof PortalAdminSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/users': {
      id: '/_portal/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof PortalAdminUsersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/dashboard': {
      id: '/_portal/employee/dashboard'
      path: '/employee/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof PortalEmployeeDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/new-order': {
      id: '/_portal/employee/new-order'
      path: '/employee/new-order'
      fullPath: '/employee/new-order'
      preLoaderRoute: typeof PortalEmployeeNewOrderRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/notifications': {
      id: '/_portal/employee/notifications'
      path: '/employee/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof PortalEmployeeNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/orders': {
      id: '/_portal/employee/orders'
      path: '/employee/orders'
      fullPath: '/employee/orders'
      preLoaderRoute: typeof PortalEmployeeOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/production/dashboard': {
      id: '/_portal/production/dashboard'
      path: '/production/dashboard'
      fullPath: '/production/dashboard'
      preLoaderRoute: typeof PortalProductionDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/production/notifications': {
      id: '/_portal/production/notifications'
      path: '/production/notifications'
      fullPath: '/production/notifications'
      preLoaderRoute: typeof PortalProductionNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/production/queue': {
      id: '/_portal/production/queue'
      path: '/production/queue'
      fullPath: '/production/queue'
      preLoaderRoute: typeof PortalProductionQueueRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/accountant/billing_/$id': {
      id: '/_portal/accountant/billing_/$id'
      path: '/accountant/billing/$id'
      fullPath: '/accountant/billing/$id'
      preLoaderRoute: typeof PortalAccountantBillingIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/edit-order/$id': {
      id: '/_portal/admin/edit-order/$id'
      path: '/admin/edit-order/$id'
      fullPath: '/admin/edit-order/$id'
      preLoaderRoute: typeof PortalAdminEditOrderIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin/orders_/$id': {
      id: '/_portal/admin/orders_/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof PortalAdminOrdersIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/edit-order/$id': {
      id: '/_portal/employee/edit-order/$id'
      path: '/employee/edit-order/$id'
      fullPath: '/employee/edit-order/$id'
      preLoaderRoute: typeof PortalEmployeeEditOrderIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/employee/orders_/$id': {
      id: '/_portal/employee/orders_/$id'
      path: '/employee/orders/$id'
      fullPath: '/employee/orders/$id'
      preLoaderRoute: typeof PortalEmployeeOrdersIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalProfileRoute: typeof PortalProfileRoute
  PortalAccountantBillingRoute: typeof PortalAccountantBillingRoute
  PortalAccountantDashboardRoute: typeof PortalAccountantDashboardRoute
  PortalAccountantFinancialYearRoute: typeof PortalAccountantFinancialYearRoute
  PortalAccountantNotificationsRoute: typeof PortalAccountantNotificationsRoute
  PortalAccountantOrdersRoute: typeof PortalAccountantOrdersRoute
  PortalAccountantReportsRoute: typeof PortalAccountantReportsRoute
  PortalAdminAuditRoute: typeof PortalAdminAuditRoute
  PortalAdminDashboardRoute: typeof PortalAdminDashboardRoute
  PortalAdminFinancialYearRoute: typeof PortalAdminFinancialYearRoute
  PortalAdminOrdersRoute: typeof PortalAdminOrdersRoute
  PortalAdminReportsRoute: typeof PortalAdminReportsRoute
  PortalAdminSettingsRoute: typeof PortalAdminSettingsRoute
  PortalAdminUsersRoute: typeof PortalAdminUsersRoute
  PortalEmployeeDashboardRoute: typeof PortalEmployeeDashboardRoute
  PortalEmployeeNewOrderRoute: typeof PortalEmployeeNewOrderRoute
  PortalEmployeeNotificationsRoute: typeof PortalEmployeeNotificationsRoute
  PortalEmployeeOrdersRoute: typeof PortalEmployeeOrdersRoute
  PortalProductionDashboardRoute: typeof PortalProductionDashboardRoute
  PortalProductionNotificationsRoute: typeof PortalProductionNotificationsRoute
  PortalProductionQueueRoute: typeof PortalProductionQueueRoute
  PortalAccountantBillingIdRoute: typeof PortalAccountantBillingIdRoute
  PortalAdminEditOrderIdRoute: typeof PortalAdminEditOrderIdRoute
  PortalAdminOrdersIdRoute: typeof PortalAdminOrdersIdRoute
  PortalEmployeeEditOrderIdRoute: typeof PortalEmployeeEditOrderIdRoute
  PortalEmployeeOrdersIdRoute: typeof PortalEmployeeOrdersIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalProfileRoute: PortalProfileRoute,
  PortalAccountantBillingRoute: PortalAccountantBillingRoute,
  PortalAccountantDashboardRoute: PortalAccountantDashboardRoute,
  PortalAccountantFinancialYearRoute: PortalAccountantFinancialYearRoute,
  PortalAccountantNotificationsRoute: PortalAccountantNotificationsRoute,
  PortalAccountantOrdersRoute: PortalAccountantOrdersRoute,
  PortalAccountantReportsRoute: PortalAccountantReportsRoute,
  PortalAdminAuditRoute: PortalAdminAuditRoute,
  PortalAdminDashboardRoute: PortalAdminDashboardRoute,
  PortalAdminFinancialYearRoute: PortalAdminFinancialYearRoute,
  PortalAdminOrdersRoute: PortalAdminOrdersRoute,
  PortalAdminReportsRoute: PortalAdminReportsRoute,
  PortalAdminSettingsRoute: PortalAdminSettingsRoute,
  PortalAdminUsersRoute: PortalAdminUsersRoute,
  PortalEmployeeDashboardRoute: PortalEmployeeDashboardRoute,
  PortalEmployeeNewOrderRoute: PortalEmployeeNewOrderRoute,
  PortalEmployeeNotificationsRoute: PortalEmployeeNotificationsRoute,
  PortalEmployeeOrdersRoute: PortalEmployeeOrdersRoute,
  PortalProductionDashboardRoute: PortalProductionDashboardRoute,
  PortalProductionNotificationsRoute: PortalProductionNotificationsRoute,
  PortalProductionQueueRoute: PortalProductionQueueRoute,
  PortalAccountantBillingIdRoute: PortalAccountantBillingIdRoute,
  PortalAdminEditOrderIdRoute: PortalAdminEditOrderIdRoute,
  PortalAdminOrdersIdRoute: PortalAdminOrdersIdRoute,
  PortalEmployeeEditOrderIdRoute: PortalEmployeeEditOrderIdRoute,
  PortalEmployeeOrdersIdRoute: PortalEmployeeOrdersIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
